#CRIANDO DATABASE
CREATE DATABASE IF NOT EXISTS CASO_IV;

#USANDO A DATABASE
USE CASO_IV;

#CRIANDO A TABELA ALUNO
CREATE TABLE IF NOT EXISTS ALUNO(
ALUNO_CPF INT PRIMARY KEY,
ALUNO_NOME VARCHAR(50) NOT NULL,
ALUNO_DATA_NASC DATE NOT NULL,
ALUNO_UF CHAR(2) NOT NULL,
ALUNO_CIDADE VARCHAR(50) NOT NULL,
ALUNO_BAIRRO VARCHAR(50) NOT NULL,
ALUNO_RUA VARCHAR(50) NOT NULL,
ALUNO_NUMRESID INT NOT NULL
);

#CRIANDO A TABELA MODALIDADE
CREATE TABLE IF NOT EXISTS MODALIDADE(
MODALIDADE_ID INT PRIMARY KEY,
MODALIDADE_NOME VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA AULA
CREATE TABLE IF NOT EXISTS AULA(
AULA_ID INT PRIMARY KEY,
AULA_CAPACIDADE INT NOT NULL,
AULA_HORÁRIO TIME NOT NULL,
AULA_MOD INT NOT NULL,
CONSTRAINT FK_MODALIDADE1 FOREIGN KEY (AULA_MOD) REFERENCES MODALIDADE(MODALIDADE_ID)
);

#CRIANDO A TABELA PAGAMENTO
CREATE TABLE IF NOT EXISTS PAGAMENTO(
PAGAMENTO_ISBN VARCHAR(17) PRIMARY KEY,
PAGAMENTO_DATA DATE NOT NULL,
PAGAMENTO_VALOR VARCHAR(10) NOT NULL,
PAGAMENTO_PAGO VARCHAR(40) NOT NULL,
PAGAMENTO_PENDENTE VARCHAR(40) NOT NULL,
PAGAMENTO_ALN INT NOT NULL,
CONSTRAINT FK_ALUNO1 FOREIGN KEY (PAGAMENTO_ALN) REFERENCES ALUNO(ALUNO_CPF)
);

#CRIANDO A TABELA INSTRUTOR
CREATE TABLE IF NOT EXISTS INSTRUTOR(
INSTRUTOR_ID INT PRIMARY KEY,
INSTRUTOR_NOME VARCHAR(50) NOT NULL,
INSTRUTOR_MDL INT NOT NULL,
CONSTRAINT FK_MODALIDADE2 FOREIGN KEY (INSTRUTOR_MDL) REFERENCES MODALIDADE(MODALIDADE_ID)
);

#CRIANDO A TABELA PLANO DE TREINAMENTO
CREATE TABLE IF NOT EXISTS PLANO_TREINAMENTO(
PLANO_TREINAMENTO_ID INT PRIMARY KEY,
PROGRESSO VARCHAR(100) NOT NULL,
PLANO_TREINAMENTO_INST INT NOT NULL,
CONSTRAINT FK_INSTRUTOR FOREIGN KEY (PLANO_TREINAMENTO_INST) REFERENCES INSTRUTOR(INSTRUTOR_ID)
);

#CRIANDO TABELAS ASSOCIATIVAS

#CRIANDO A TABELA ALUNO_MOD (ENTIDADE ASSOCIATIVA ENTRE ALUNO E MODALIDADE)
CREATE TABLE IF NOT EXISTS ALUNO_MOD(
ALN_MDL INT NOT NULL,
MDL_ALN INT NOT NULL,
CONSTRAINT FK_ALUNO2 FOREIGN KEY (ALN_MDL) REFERENCES ALUNO(ALUNO_CPF),
CONSTRAINT FK_MODALIDADE3 FOREIGN KEY (MDL_ALN) REFERENCES MODALIDADE(MODALIDADE_ID)
);

#ALUNO
ALTER TABLE ALUNO ADD ALUNO_DATA_MATRICULA DATE NOT NULL;
ALTER TABLE ALUNO DROP COLUMN ALUNO_RUA;
ALTER TABLE ALUNO MODIFY COLUMN ALUNO_NOME VARCHAR(100);
ALTER TABLE ALUNO CHANGE COLUMN ALUNO_NUMRESID ALUNO_NUMERO_RESIDENCIA INT;

#MODALIDADE
ALTER TABLE MODALIDADE ADD MODALIDADE_DESCRICAO VARCHAR(100);
ALTER TABLE MODALIDADE DROP COLUMN MODALIDADE_DESCRICAO;
ALTER TABLE MODALIDADE MODIFY COLUMN MODALIDADE_NOME VARCHAR(100);
ALTER TABLE MODALIDADE CHANGE COLUMN MODALIDADE_NOME MODALIDADE_NOME_COMPLETO VARCHAR(100);

#AULA
ALTER TABLE AULA ADD AULA_DURACAO TIME NOT NULL;
ALTER TABLE AULA DROP COLUMN AULA_CAPACIDADE;
ALTER TABLE AULA MODIFY COLUMN AULA_HORÁRIO DATETIME;
ALTER TABLE AULA CHANGE COLUMN AULA_HORÁRIO AULA_DATA_HORA DATETIME;

#PAGAMENTO
ALTER TABLE PAGAMENTO ADD PAGAMENTO_METODO VARCHAR(50) NOT NULL;
ALTER TABLE PAGAMENTO DROP COLUMN PAGAMENTO_PENDENTE;
ALTER TABLE PAGAMENTO MODIFY COLUMN PAGAMENTO_VALOR DECIMAL(10, 2);
ALTER TABLE PAGAMENTO CHANGE COLUMN PAGAMENTO_PAGO PAGAMENTO_STATUS VARCHAR(20);

#INSTRUTOR
ALTER TABLE INSTRUTOR ADD INSTRUTOR_DATA_CONTRATACAO DATE NOT NULL;
ALTER TABLE INSTRUTOR DROP COLUMN INSTRUTOR_DATA_CONTRATACAO;
ALTER TABLE INSTRUTOR MODIFY COLUMN INSTRUTOR_NOME VARCHAR(100);
ALTER TABLE INSTRUTOR CHANGE COLUMN INSTRUTOR_MDL INSTRUTOR_MODALIDADE INT;

#PLANO_TREINAMENTO
ALTER TABLE PLANO_TREINAMENTO ADD PLANO_TREINAMENTO_NOME VARCHAR(100) NOT NULL;
ALTER TABLE PLANO_TREINAMENTO DROP COLUMN PROGRESSO;
ALTER TABLE PLANO_TREINAMENTO MODIFY COLUMN PLANO_TREINAMENTO_INST INT;
ALTER TABLE PLANO_TREINAMENTO CHANGE COLUMN PLANO_TREINAMENTO_INST INSTRUTOR_RESPONSAVEL INT;

#ALUNO_MOD
ALTER TABLE ALUNO_MOD ADD DATA_INICIO DATE NOT NULL;
ALTER TABLE ALUNO_MOD DROP COLUMN MDL_ALN;
ALTER TABLE ALUNO_MOD ADD MDL_ALUNO INT NOT NULL;
ALTER TABLE ALUNO_MOD CHANGE COLUMN ALN_MDL ALUNO_ID INT NOT NULL;