#CRIANDO DATABASE CASO_V
CREATE DATABASE IF NOT EXISTS CASO_V;

#USANDO A DATABASE
USE CASO_V;

#CRIANDO A TABELA CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE(
CLIENTE_CPF VARCHAR(20) PRIMARY KEY,
CLIENTE_DATANASC DATE NOT NULL,
CLIENTE_UF CHAR(2) NOT NULL,
CLIENTE_CIDADE VARCHAR(40) NOT NULL,
CLIENTE_BAIRRO VARCHAR(40) NOT NULL,
CLIENTE_RUA VARCHAR(40) NOT NULL,
CLIENTE_NUMRES INT NOT NULL
);

#CRIANDO A TABELA FORNECEDOR
CREATE TABLE IF NOT EXISTS FORNECEDOR(
FORNECEDOR_ID INT PRIMARY KEY,
FORNECEDOR_NOME VARCHAR(40) NOT NULL
);

#CRIANDO A TABELA PRODUTO
CREATE TABLE IF NOT EXISTS PRODUTO(
PRODUTO_ISBN VARCHAR(20) PRIMARY KEY,
PRODUTO_ESTOQUE INT NOT NULL,
PRODUTO_PRECO VARCHAR(10) NOT NULL,
PRODUTO_FORN INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PRODUTO_FORN) REFERENCES FORNECEDOR(FORNECEDOR_ID)
);

#CRIANDO A TABELA VENDA
CREATE TABLE IF NOT EXISTS VENDA(
VENDA_ID INT PRIMARY KEY,
VENDA_CLIE VARCHAR(20) NOT NULL,
CONSTRAINT FK_CLIENTE1 FOREIGN KEY (VENDA_CLIE) REFERENCES CLIENTE(CLIENTE_CPF)
);

#CRIANDO A TABELA PAGAMENTO
CREATE TABLE IF NOT EXISTS PAGAMENTO(
PAGAMENTO_ISBN VARCHAR(20) PRIMARY KEY,
PAGAMENTO_DATA DATE NOT NULL,
PAGAMENTO_VALOR VARCHAR(10) NOT NULL,
PAGAMENTO_PAGO VARCHAR(50) NOT NULL,
PAGAMENTO_PENDENTE VARCHAR(50) NOT NULL,
PAGAMENTO_CLIE VARCHAR(20) NOT NULL,
CONSTRAINT FK_CLIENTE2 FOREIGN KEY (PAGAMENTO_CLIE) REFERENCES CLIENTE(CLIENTE_CPF)
);

#ABAIXO ESTÃO AS TABELAS ASSOCIATIVAS

#CRIANDO A TABELA VENDA_PROD (ASSOCIATIVA ENTRE A TABELA VENDA E PRODUTO)
CREATE TABLE IF NOT EXISTS VENDA_PROD(
PROD_VENDA VARCHAR(20),
VENDA_PROD INT,
PRIMARY KEY (PROD_VENDA,VENDA_PROD),
CONSTRAINT FK_PRODUTO FOREIGN KEY (PROD_VENDA) REFERENCES PRODUTO(PRODUTO_ISBN),
CONSTRAINT FK_VENDA FOREIGN KEY (VENDA_PROD) REFERENCES VENDA(VENDA_ID)
);

#ABAIXO SERÃO APRESENTADOS O ALTER TABLE PARA CADA TABELA

#CLIENTE
ALTER TABLE CLIENTE ADD CLIENTE_EMAIL VARCHAR(50) NOT NULL;
ALTER TABLE CLIENTE DROP COLUMN CLIENTE_EMAIL;
ALTER TABLE CLIENTE MODIFY COLUMN CLIENTE_CIDADE VARCHAR(50);
ALTER TABLE CLIENTE CHANGE COLUMN CLIENTE_NUMRES CLIENTE_NUMERO_RESIDENCIA INT;

#FORNECEDOR
ALTER TABLE FORNECEDOR ADD FORNECEDOR_ENDERECO VARCHAR(100) NOT NULL;
ALTER TABLE FORNECEDOR DROP COLUMN FORNECEDOR_ENDERECO;
ALTER TABLE FORNECEDOR MODIFY COLUMN FORNECEDOR_NOME VARCHAR(100);
ALTER TABLE FORNECEDOR CHANGE COLUMN FORNECEDOR_NOME FORNECEDOR_RAZAO_SOCIAL VARCHAR(150);

#PRODUTO
ALTER TABLE PRODUTO ADD PRODUTO_DESCRICAO TEXT NOT NULL;
ALTER TABLE PRODUTO DROP COLUMN PRODUTO_DESCRICAO;
ALTER TABLE PRODUTO MODIFY COLUMN PRODUTO_PRECO DECIMAL(10, 2);
ALTER TABLE PRODUTO CHANGE COLUMN PRODUTO_ESTOQUE PRODUTO_QTD_ESTOQUE INT;

#VENDA
ALTER TABLE VENDA ADD VENDA_DATA DATE NOT NULL;
ALTER TABLE VENDA DROP COLUMN VENDA_DATA;
ALTER TABLE VENDA MODIFY COLUMN VENDA_CLIE VARCHAR(30);
ALTER TABLE VENDA CHANGE COLUMN VENDA_CLIE CLIENTE_CPF_VENDA VARCHAR(30);

#PAGAMENTO
ALTER TABLE PAGAMENTO ADD PAGAMENTO_METODO VARCHAR(50) NOT NULL;
ALTER TABLE PAGAMENTO DROP COLUMN PAGAMENTO_METODO;
ALTER TABLE PAGAMENTO MODIFY COLUMN PAGAMENTO_VALOR DECIMAL(10, 2);
ALTER TABLE PAGAMENTO CHANGE COLUMN PAGAMENTO_PAGO PAGAMENTO_STATUS VARCHAR(20);

#VENDA_PROD
ALTER TABLE VENDA_PROD ADD QUANTIDADE INT NOT NULL;
ALTER TABLE VENDA_PROD DROP COLUMN QUANTIDADE;
ALTER TABLE VENDA_PROD MODIFY COLUMN PROD_VENDA VARCHAR(30);
ALTER TABLE VENDA_PROD CHANGE COLUMN VENDA_PROD VENDA_ID_PRODUTO INT;