#CRIANDO DATABSE CASO_I
CREATE DATABASE IF NOT EXISTS CASO_I;

USE CASO_I;

#CRIANDO A TABELA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

#CRIANDO A TABELA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL
);

#CRIANDO A TABELA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

#ABAIXO, AS TABELAS COM DEPENDÊNCIA DE CHAVE(S) ESTRANGEIRA(S)

#CRIANDO A TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD)
);

#CRIANDO A TABELA RECEBIMENTOS (VEIO DEPOIS POIS TEM DEPENDÊNCIA DE PEDIDOS)
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

#ABAIXO, AS TABELAS ASSOCIATIVAS

#CRIANDO A TABELA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#CRIANDO A TABELA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

#CRIAR A TABELA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));

#ABAIXO SERÃO APRESENTADOS O ALTER TABLE PARA CADA TABELA

#FORNECEDORES
ALTER TABLE FORNECEDORES ADD FORNEC_DATA_CRIACAO DATE NOT NULL;
ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_RUA;
ALTER TABLE FORNECEDORES MODIFY COLUMN FORNEC_NOME VARCHAR(100);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNEC_NOME FORNEC_NOME_COMPLETO VARCHAR(150);

#FILIAIS
ALTER TABLE FILIAIS ADD FILIAL_DATA_CRIACAO DATE NOT NULL;
ALTER TABLE FILIAIS DROP COLUMN FILIAL_PAIS;
ALTER TABLE FILIAIS MODIFY COLUMN FILIAL_NOME VARCHAR(100);
ALTER TABLE FILIAIS CHANGE COLUMN FILIAL_NOME FILIAL_NOME_COMPLETO VARCHAR(150);

#PRODUTOS
ALTER TABLE PRODUTOS ADD PROD_DATA_VENCIMENTO DATE NOT NULL;
ALTER TABLE PRODUTOS DROP COLUMN PROD_QUANT;
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_NOME VARCHAR(100);
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_DESCRICAO PROD_DESCRICAO_COMPLETA VARCHAR(150);

#PEDIDOS
ALTER TABLE PEDIDOS ADD PED_TIPO VARCHAR(50) NOT NULL;
ALTER TABLE PEDIDOS DROP COLUMN PED_HORA;
ALTER TABLE PEDIDOS MODIFY COLUMN PED_DATA DATETIME;
ALTER TABLE PEDIDOS CHANGE COLUMN PED_DATA PED_DATA_HORA DATETIME;

#RECEBIMENTOS
ALTER TABLE RECEBIMENTOS ADD RECEB_STATUS VARCHAR(50) NOT NULL;
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_HORA;
ALTER TABLE RECEBIMENTOS MODIFY COLUMN RECEB_DATA DATETIME;
ALTER TABLE RECEBIMENTOS CHANGE COLUMN RECEB_DATA RECEB_DATA_HORA DATETIME;

#PEDIDOS_PRODUTOS
ALTER TABLE PEDIDOS_PRODUTOS ADD PDPR_CONDICAO VARCHAR(50) NOT NULL;
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PDPR_CONDICAO;
ALTER TABLE PEDIDOS_PRODUTOS MODIFY COLUMN PDPR_QUANT DECIMAL(10,4);
ALTER TABLE PEDIDOS_PRODUTOS CHANGE COLUMN PDPR_QUANT PDPR_QUANTIDADE DECIMAL(10,4);

#FILIAIS_PRODUTOS
ALTER TABLE FILIAIS_PRODUTOS ADD FLPR_CONDICAO VARCHAR(50) NOT NULL;
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FLPR_CONDICAO;
ALTER TABLE FILIAIS_PRODUTOS MODIFY COLUMN FLPR_QUANT DECIMAL(10,4);
ALTER TABLE FILIAIS_PRODUTOS CHANGE COLUMN FLPR_QUANT FLPR_QUANTIDADE DECIMAL(10,4);