#CRIANDO DATABASE CASO_II
CREATE DATABASE IF NOT EXISTS CASO_II;

#USANDO A DATABASE
USE CASO_II;

#CRIANDO A TABELA PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TELEFONE VARCHAR(20) NOT NULL,
PASS_UF CHAR(2) NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_RUA VARCHAR(50) NOT NULL,
PASS_NUMRESID INT NOT NULL,
PASS_EMAIL VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_PAIS VARCHAR(50) NOT NULL,
AEROP_LATITUDE VARCHAR(50) NOT NULL,
AEROP_LONGITUDE VARCHAR(50) NOT NULL,
AEROP_VOO_ORIGEM VARCHAR(40) NOT NULL,
AEROP_VOO_DESTINO VARCHAR(40) NOT NULL
);

#CRIANDO A TABELA AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO VARCHAR(20) PRIMARY KEY,
AERON_MODELO VARCHAR(50) NOT NULL,
AERON_ANOFABR DATE NOT NULL,
AERON_FABRICANTE VARCHAR(50) NOT NULL,
AERON_CAPACIDADE INT NOT NULL,
AERON_AUTONOMIA VARCHAR (50) NOT NULL
);

#CRIANDO A TABELA VOOS
CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP INT NOT NULL,
VOO_AERON VARCHAR(20) NOT NULL,
CONSTRAINT FK_AEROP_AERON FOREIGN KEY (VOO_AEROP) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT FK_AEORON1 FOREIGN KEY (VOO_AERON) REFERENCES AERONAVES(AERON_PREFIXO)
);

#CRIANDO A TABELA FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_UF CHAR(2) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_BAIRRO VARCHAR(50) NOT NULL,
FUNC_RUA VARCHAR(50) NOT NULL,
FUNC_NUMRESID INT NOT NULL,
FUNC_CPF VARCHAR(15) NOT NULL,
FUNC_FUNCAO VARCHAR(50) NOT NULL
);

#ABAIXO ESTÃO AS ENTIDADES ASSOCIATIVAS

#CRIANDO A TABELA EQUIPES
CREATE TABLE IF NOT EXISTS EQUIPES(
EQP_FUNC INT,
EQP_VOO INT,
PRIMARY KEY(EQP_FUNC, EQP_VOO),
CONSTRAINT FK_FUNCIONARIOS1 FOREIGN KEY (EQP_FUNC) REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT FK_VOOS1 FOREIGN KEY (EQP_VOO) REFERENCES VOOS(VOO_ID)
);

#CRIANDO A TABELA RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS(
RESERVA_COD INT PRIMARY KEY,
RES_VOO INT NOT NULL,
RES_PASS INT NOT NULL,
CONSTRAINT FK_VOOS2 FOREIGN KEY (RES_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_PASS1 FOREIGN KEY (RES_PASS) REFERENCES PASSAGEIROS(PASS_CPF)
);

#ABAIXO SERÃO APRESENTADOS O ALTER TABLE PARA CADA TABELA

#PASSAGEIROS
ALTER TABLE PASSAGEIROS ADD PASS_DATA_CADASTRO DATE NOT NULL;
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_RUA;
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_NOME VARCHAR(100);
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_NOME PASS_NOME_COMPLETO VARCHAR(150);

#AEROPORTOS
ALTER TABLE AEROPORTOS ADD AEROP_DATA_CRIACAO DATE NOT NULL;
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_LONGITUDE;
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_NOME VARCHAR(100);
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_NOME AEROP_NOME_COMPLETO VARCHAR(150);

#AERONAVES
ALTER TABLE AERONAVES ADD AERON_DATA_INSPECAO DATE NOT NULL;
ALTER TABLE AERONAVES DROP COLUMN AERON_AUTONOMIA;
ALTER TABLE AERONAVES MODIFY COLUMN AERON_MODELO VARCHAR(100);
ALTER TABLE AERONAVES CHANGE COLUMN AERON_MODELO AERON_MODELO_COMPLETO VARCHAR(150);

#VOOS
ALTER TABLE VOOS ADD VOO_TIPO VARCHAR(50) NOT NULL;
ALTER TABLE VOOS DROP COLUMN VOO_HORA;
ALTER TABLE VOOS MODIFY COLUMN VOO_DATA DATETIME;
ALTER TABLE VOOS CHANGE COLUMN VOO_DATA VOO_DATA_HORA DATETIME;

#FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD FUNC_DATA_ADMISSAO DATE NOT NULL;
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_RUA;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_NOME VARCHAR(100);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_NOME FUNC_NOME_COMPLETO VARCHAR(150);