#CRIANDO A DATABASE CASO_III
CREATE DATABASE IF NOT EXISTS CASO_III;

#USANDO A DATABASE
USE CASO_III;

#CRIANDO A TABELA CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE(
CLIENTE_COD INT PRIMARY KEY,
CLIENTE_CNPJ VARCHAR(18) NOT NULL,
CLIENTE_RAZSOC VARCHAR(50) NOT NULL,
CLIENTE_RAMOATV VARCHAR(50) NOT NULL,
CLIENTE_DATACADAST DATE NOT NULL,
CLIENTE_PESSOACONT VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA EMPREGADO
CREATE TABLE IF NOT EXISTS EMPREGADO(
EMPREGADO_MATRÍCULA INT PRIMARY KEY,
EMPREGADO_NOME VARCHAR(50) NOT NULL,
EMPREGADO_CARGO VARCHAR(50) NOT NULL,
EMPREGADO_SALÁRIO VARCHAR(10) NOT NULL,
EMPREGADO_DATA_ADMIS DATE NOT NULL,
EMPREGADO_QUALIFIC VARCHAR(100) NOT NULL
);

#CRIANDO A TABELA FORNECEDOR
CREATE TABLE IF NOT EXISTS FORNECEDOR(
FORNEC_CNPJ VARCHAR(18) PRIMARY KEY,
FORNEC_RAZSOC VARCHAR(50) NOT NULL,
FORNEC_PESSOACONT VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA ENCOMENDA
CREATE TABLE IF NOT EXISTS ENCOMENDA(
ENCOMENDA_NUM INT PRIMARY KEY,
ENCOMENDA_DATA_INC DATE NOT NULL,
ENCOMENDA_CLIENTE INT NOT NULL,
CONSTRAINT FK_CLIENTE1 FOREIGN KEY (ENCOMENDA_CLIENTE) REFERENCES CLIENTE(CLIENTE_COD)
);

#CRIANDO A TABELA FORMA DE PAGAMENTO
CREATE TABLE IF NOT EXISTS FORMA_PAGAMENTO(
FORM_PAG_ID INT PRIMARY KEY,
FORM_PAG_VALTOT VARCHAR(20) NOT NULL,
FORM_PAG_VALDESC VARCHAR(20) NOT NULL,
FORM_PAG_VALLIQ VARCHAR(20) NOT NULL,
FORM_PAG_QTDPARCE INT NOT NULL,
FORM_PAG_ENCOM INT NOT NULL,
CONSTRAINT FK_ENCOMENDA1 FOREIGN KEY (FORM_PAG_ENCOM) REFERENCES ENCOMENDA(ENCOMENDA_NUM)
);

#CRIANDO A TABELA PRODUTO
CREATE TABLE IF NOT EXISTS PRODUTO(
PRODUTO_COD INT PRIMARY KEY,
PRODUTO_NOME VARCHAR(50) NOT NULL,
PRODUTO_COR VARCHAR(50) NOT NULL,
PRODUTO_DIMENSÕES VARCHAR(50) NOT NULL,
PRODUTO_PREÇO VARCHAR(50) NOT NULL,
PRODUTO_TEMPFAB TIME NOT NULL,
PRODUTO_DESENHO VARCHAR(50) NOT NULL,
PRODUTO_HRMÃO_OBRA TIME NOT NULL,
PRODUTO_ENCOM INT NOT NULL,
CONSTRAINT FK_ENCOMENDA2 FOREIGN KEY (PRODUTO_ENCOM) REFERENCES ENCOMENDA(ENCOMENDA_NUM)
);

#CRIANDO A TABELA PROD_MAQ (ENTIDADE ASSOCIATIVA)
CREATE TABLE IF NOT EXISTS PROD_MAQ(
PROD_MAQ_KEY INT PRIMARY KEY,
PROD_MAQ_TIPO VARCHAR(50) NOT NULL,
CONSTRAINT FK_PRODUTO1 FOREIGN KEY (PROD_MAQ_KEY) REFERENCES PRODUTO(PRODUTO_COD)
);

#CRIANDO A TABELA EMP_PROD (ENTIDADE ASSOCIATIVA)
CREATE TABLE IF NOT EXISTS EMP_PROD(
EMPREGADO_PRODUTO INT,
PRODUTO_EMPREGADO INT,
PRIMARY KEY (EMPREGADO_PRODUTO,PRODUTO_EMPREGADO),
CONSTRAINT FK_EMPREGADO1 FOREIGN KEY (EMPREGADO_PRODUTO) REFERENCES EMPREGADO(EMPREGADO_MATRÍCULA),
CONSTRAINT FK_PRODUTO2 FOREIGN KEY (PRODUTO_EMPREGADO) REFERENCES PRODUTO(PRODUTO_COD)
);

#CRIANDO A TABELA MÁQUINA
CREATE TABLE IF NOT EXISTS MAQUINA(
MAQ_PROD INT PRIMARY KEY,
MAQ_TEMPO_VIDA VARCHAR(10) NOT NULL,
MAQ_DATA_COMPRA DATE NOT NULL,
MAQ_DATA_GARANTIA DATE NOT NULL,
CONSTRAINT FK_PRODUTO3 FOREIGN KEY (MAQ_PROD) REFERENCES PROD_MAQ(PROD_MAQ_KEY)
);

#CRIANDO A TABELA REGISTRO DE MANUTENÇÃO
CREATE TABLE IF NOT EXISTS RM(
RM_MAQ_PROD INT PRIMARY KEY,
RM_DATA DATE NOT NULL,
RM_DESCRICAO VARCHAR(50) NOT NULL,
CONSTRAINT FK_MAQUINA1 FOREIGN KEY (RM_MAQ_PROD) REFERENCES MAQUINA(MAQ_PROD)
);

#CRIANDO A TABELA RECURSOS ESPECÍFICOS
CREATE TABLE IF NOT EXISTS RE(
RE_PRODUTO INT NOT NULL,
RE_QTD_NECESS INT NOT NULL,
RE_UNIDADE INT NOT NULL,
RE_TEMPO_USO TIME NOT NULL,
RE_HRMÃO_OBRA TIME NOT NULL,
CONSTRAINT FK_PRODUTO4 FOREIGN KEY (RE_PRODUTO) REFERENCES PRODUTO(PRODUTO_COD)
);

#CRIANDO A TABELA COMPONENTE
CREATE TABLE IF NOT EXISTS COMPONENTE(
COMPONENTE_COD INT PRIMARY KEY,
COMPONENTE_NOME VARCHAR(50) NOT NULL,
COMPONENTE_QTD_ESTOQUE INT NOT NULL,
COMPONENTE_PRECO_U VARCHAR(10) NOT NULL,
COMPONENTE_U INT NOT NULL,
COMPONENTE_PROD INT NOT NULL,
COMPONENTE_FORNEC VARCHAR(18) NOT NULL,
CONSTRAINT FK_PRODUTO5 FOREIGN KEY (COMPONENTE_PROD) REFERENCES PRODUTO(PRODUTO_COD),
CONSTRAINT FK_FORNECEDDOR1 FOREIGN KEY (COMPONENTE_FORNEC) REFERENCES FORNECEDOR(FORNEC_CNPJ)
);

#CRIANDO A TABELA TIPO DE COMPONENTE
CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE(
TIPO_COMP_COD INT PRIMARY KEY,
TIPO_COMP_NOME VARCHAR(50) NOT NULL,
TIPO_COMP_COMP INT NOT NULL,
CONSTRAINT FK_COMPONENTE1 FOREIGN KEY (TIPO_COMP_COMP) REFERENCES COMPONENTE(COMPONENTE_COD)
);

#CRIANDO A TABELA REGISTRO DE SUPRIMENTO
CREATE TABLE IF NOT EXISTS RS(
RS_COMPONENTE INT PRIMARY KEY,
RS_QTD VARCHAR(20) NOT NULL,
RS_DATA_NECES DATE NOT NULL,
CONSTRAINT FK_COMPONENTE2 FOREIGN KEY (RS_COMPONENTE) REFERENCES COMPONENTE(COMPONENTE_COD)
);

#CRIANDO A TABELA EMPRESA (ENTIDADE ASSOCIATIVA)
CREATE TABLE IF NOT EXISTS EMPRESA(
EMPRESA_CNPJ VARCHAR(18) PRIMARY KEY,
EMPRESA_CLIENTE INT NOT NULL,
EMPRESA_FORNEC VARCHAR(18) NOT NULL,
EMPRESA_RAZSOC VARCHAR(50) NOT NULL,
EMPRESA_PESSOACONT VARCHAR(50) NOT NULL,
CONSTRAINT FK_CLIENTE2 FOREIGN KEY (EMPRESA_CLIENTE) REFERENCES CLIENTE(CLIENTE_COD),
CONSTRAINT FK_FORNECEDOR2 FOREIGN KEY (EMPRESA_FORNEC) REFERENCES FORNECEDOR(FORNEC_CNPJ)
);

#CRIANDO A TABELA TIPO DE ENDEREÇO
CREATE TABLE IF NOT EXISTS TIPO_ENDERECO(
TIPO_ENDER_COD INT PRIMARY KEY,
TIPO_ENDER_NOME VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA ENDEREÇO
CREATE TABLE IF NOT EXISTS ENDERECO(
ENDERECO_TIPO_ENDER INT PRIMARY KEY,
ENDERECO_NUM INT NOT NULL,
ENDERECO_LOGRAD VARCHAR(50) NOT NULL,
ENDERECO_COMPLEM VARCHAR(50) NOT NULL,
ENDERECO_CEP VARCHAR(10) NOT NULL,
ENDERECO_BAIRRO VARCHAR(50) NOT NULL,
ENDERECO_CIDADE VARCHAR(50) NOT NULL,
ENDERECO_ESTADO VARCHAR(50) NOT NULL,
ENDERECO_CLIENTE INT NOT NULL,
ENDERECO_EMPREGADO INT NOT NULL,
ENDERECO_EMPRESA VARCHAR(18) NOT NULL,
ENDERECO_FORNECEDOR VARCHAR(18) NOT NULL,
CONSTRAINT FK_TIPO_ENDERECO1 FOREIGN KEY (ENDERECO_TIPO_ENDER) REFERENCES TIPO_ENDERECO(TIPO_ENDER_COD),
CONSTRAINT FK_CLIENTE3 FOREIGN KEY (ENDERECO_CLIENTE) REFERENCES CLIENTE(CLIENTE_COD),
CONSTRAINT FK_EMPREGADO2 FOREIGN KEY (ENDERECO_EMPREGADO) REFERENCES EMPREGADO(EMPREGADO_MATRÍCULA),
CONSTRAINT FK_EMPRESA1 FOREIGN KEY (ENDERECO_EMPRESA) REFERENCES EMPRESA(EMPRESA_CNPJ),
CONSTRAINT FK_FORNECEDOR3 FOREIGN KEY (ENDERECO_FORNECEDOR) REFERENCES FORNECEDOR(FORNEC_CNPJ)
);

#CRIANDO A TABELA TELEFONE
CREATE TABLE IF NOT EXISTS TELEFONE(
TELEFONE_TIPO VARCHAR(10) NOT NULL,
TELEFONE_DDD VARCHAR(5) NOT NULL,
TELEFONE_CLIENTE INT NOT NULL,
TELEFONE_EMPREGADO INT NOT NULL,
TELEFONE_EMPRESA VARCHAR(18) NOT NULL,
TELEFONE_FORNECEDOR VARCHAR(18) NOT NULL,
CONSTRAINT FK_CLIENTE4 FOREIGN KEY (TELEFONE_CLIENTE) REFERENCES CLIENTE(CLIENTE_COD),
CONSTRAINT FK_EMPREGADO3 FOREIGN KEY (TELEFONE_EMPREGADO) REFERENCES EMPREGADO(EMPREGADO_MATRÍCULA),
CONSTRAINT FK_EMPRESA2 FOREIGN KEY (TELEFONE_EMPRESA) REFERENCES EMPRESA(EMPRESA_CNPJ),
CONSTRAINT FK_FORNECEDOR4 FOREIGN KEY (TELEFONE_FORNECEDOR) REFERENCES FORNECEDOR(FORNEC_CNPJ)
);

#ABAIXO SERÃO APRESENTADOS O ALTER TABLE PARA CADA TABELA

#CLIENTE
ALTER TABLE CLIENTE ADD CLIENTE_DATA_ATUALIZACAO DATE NOT NULL;
ALTER TABLE CLIENTE DROP COLUMN CLIENTE_RAMOATV;
ALTER TABLE CLIENTE MODIFY COLUMN CLIENTE_RAZSOC VARCHAR(100);
ALTER TABLE CLIENTE CHANGE COLUMN CLIENTE_RAZSOC CLIENTE_RAZAO_SOCIAL VARCHAR(150);

#EMPREGADO
ALTER TABLE EMPREGADO ADD EMPREGADO_DATA_PROMOCAO DATE;
ALTER TABLE EMPREGADO DROP COLUMN EMPREGADO_QUALIFIC;
ALTER TABLE EMPREGADO MODIFY COLUMN EMPREGADO_NOME VARCHAR(100);
ALTER TABLE EMPREGADO CHANGE COLUMN EMPREGADO_SALÁRIO EMPREGADO_SALARIO DECIMAL(15,2);

#FORNECEDOR
ALTER TABLE FORNECEDOR ADD FORNEC_EMAIL VARCHAR(100);
ALTER TABLE FORNECEDOR DROP COLUMN FORNEC_PESSOACONT;
ALTER TABLE FORNECEDOR MODIFY COLUMN FORNEC_RAZSOC VARCHAR(100);
ALTER TABLE FORNECEDOR CHANGE COLUMN FORNEC_RAZSOC FORNEC_RAZAO_SOCIAL VARCHAR(150);

#ENCOMENDA
ALTER TABLE ENCOMENDA ADD ENCOMENDA_VALOR_TOTAL DECIMAL(10, 2) NOT NULL;
ALTER TABLE ENCOMENDA DROP COLUMN ENCOMENDA_CLIENTE;
ALTER TABLE ENCOMENDA MODIFY COLUMN ENCOMENDA_DATA_INC DATETIME;
ALTER TABLE ENCOMENDA CHANGE COLUMN ENCOMENDA_DATA_INC ENCOMENDA_DATA_HORA_INC DATETIME;

#PRODUTO
ALTER TABLE PRODUTO ADD PRODUTO_DATA_EXP DATE NOT NULL;
ALTER TABLE PRODUTO DROP COLUMN PRODUTO_DIMENSÕES;
ALTER TABLE PRODUTO MODIFY COLUMN PRODUTO_NOME VARCHAR(100);
ALTER TABLE PRODUTO CHANGE COLUMN PRODUTO_PREÇO PRODUTO_PRECO_UNIT DECIMAL(10,2);

#MAQUINA
ALTER TABLE MAQUINA ADD MAQ_STATUS VARCHAR(50) NOT NULL;
ALTER TABLE MAQUINA DROP COLUMN MAQ_STATUS;
ALTER TABLE MAQUINA MODIFY COLUMN MAQ_TEMPO_VIDA INT;
ALTER TABLE MAQUINA CHANGE COLUMN MAQ_TEMPO_VIDA MAQ_TEMPO_VIDA_ANOS INT;

#RM
ALTER TABLE RM ADD RM_CUSTO DECIMAL(10,2) NOT NULL;
ALTER TABLE RM DROP COLUMN RM_CUSTO;
ALTER TABLE RM MODIFY COLUMN RM_DATA DATETIME;
ALTER TABLE RM CHANGE COLUMN RM_DATA RM_DATA_HORA DATETIME;

#RE
ALTER TABLE RE ADD RE_CUSTO_MATERIAL DECIMAL(10,2) NOT NULL;
ALTER TABLE RE DROP COLUMN RE_CUSTO_MATERIAL;
ALTER TABLE RE MODIFY COLUMN RE_QTD_NECESS INT;
ALTER TABLE RM CHANGE COLUMN RE_QTD_NECESS RE_QTD_NECESSARIA INT;

#COMPONENTE
ALTER TABLE COMPONENTE ADD COMPONENTE_DATA_COMPRA DATE NOT NULL;
ALTER TABLE COMPONENTE DROP COLUMN COMPONENTE_DATA_COMPRA;
ALTER TABLE COMPONENTE MODIFY COLUMN COMPONENTE_NOME VARCHAR(100);
ALTER TABLE COMPONENTE CHANGE COLUMN COMPONENTE_U COMPONENTE_UNIDADE VARCHAR(10);

#TIPO_COMPONENTE
ALTER TABLE TIPO_COMPONENTE ADD TIPO_COMP_DESCRICAO VARCHAR(100);
ALTER TABLE TIPO_COMPONENTE DROP COLUMN TIPO_COMP_DESCRICAO;
ALTER TABLE TIPO_COMPONENTE MODIFY COLUMN TIPO_COMP_NOME VARCHAR(100);
ALTER TABLE TIPO_COMPONENTE CHANGE COLUMN TIPO_COMP_NOME TIPO_COMP_NOME_DETALHADO VARCHAR(150);

#RS
ALTER TABLE RS ADD RS_VALOR_UNIT DECIMAL(10, 2) NOT NULL;
ALTER TABLE RS DROP COLUMN RS_VALOR_UNIT;
ALTER TABLE RS MODIFY COLUMN RS_QTD INT NOT NULL;
ALTER TABLE RS CHANGE COLUMN RS_DATA_NECES RS_DATA_NECESSIDADE DATE NOT NULL;

#EMPRESA
ALTER TABLE EMPRESA ADD EMPRESA_TIPO VARCHAR(50) NOT NULL;
ALTER TABLE EMPRESA DROP COLUMN EMPRESA_PESSOACONT;
ALTER TABLE EMPRESA MODIFY COLUMN EMPRESA_RAZSOC VARCHAR(100);
ALTER TABLE EMPRESA CHANGE COLUMN EMPRESA_RAZSOC EMPRESA_RAZAO_SOCIAL VARCHAR(150);

#TIPO_ENDERECO
ALTER TABLE TIPO_ENDERECO ADD TIPO_ENDER_DESCRICAO VARCHAR(100);
ALTER TABLE TIPO_ENDERECO DROP COLUMN TIPO_ENDER_DESCRICAO;
ALTER TABLE TIPO_ENDERECO MODIFY COLUMN TIPO_ENDER_NOME VARCHAR(100);
ALTER TABLE TIPO_ENDERECO CHANGE COLUMN TIPO_ENDER_NOME TIPO_ENDER_NOME_DETALHADO VARCHAR(150);

#ENDERECO
ALTER TABLE ENDERECO ADD ENDERECO_DATA_CAD DATE NOT NULL;
ALTER TABLE ENDERECO DROP COLUMN ENDERECO_COMPLEM;
ALTER TABLE ENDERECO MODIFY COLUMN ENDERECO_LOGRAD VARCHAR(100);
ALTER TABLE ENDERECO CHANGE COLUMN ENDERECO_CEP ENDERECO_CEP_FORMATADO VARCHAR(15);

#TELEFONE
ALTER TABLE TELEFONE ADD TELEFONE_NUMERO VARCHAR(15) NOT NULL;
ALTER TABLE TELEFONE DROP COLUMN TELEFONE_NUMERO;
ALTER TABLE TELEFONE MODIFY COLUMN TELEFONE_TIPO VARCHAR(20);
ALTER TABLE TELEFONE CHANGE COLUMN TELEFONE_DDD TELEFONE_COD_AREA VARCHAR(5);